name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.4.0

    - name: Install dependencies
      run: npm ci

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        script: |
          cd /var/www/daily-booster/daily-booster-fe
          git pull
          npm run start
          pm2 restart daily-booster-fe
